<?php

// !!!! Do not edit this File with TextMate. Saving will corrupt one Unicode character (U+1D11E).

require_once('CSSParser.php');

class CSSParserTests extends PHPUnit_Framework_TestCase {
	function testCssFiles() {
		
		$sDirectory = dirname(__FILE__).DIRECTORY_SEPARATOR.'files';
		if($rHandle = opendir($sDirectory)) {
			/* This is the correct way to loop over the directory. */
			while (false !== ($sFileName = readdir($rHandle))) {
				if(strpos($sFileName, '.') === 0) {
					continue;
				}
				if(strrpos($sFileName, '.css') !== strlen($sFileName)-strlen('.css')) {
					continue;
				}
				if(strpos($sFileName, '-') === 0) {
					//Either a file which SHOULD fail or a future test of a as-of-now missing feature
					continue;
				}
				$oParser = new CSSParser(file_get_contents($sDirectory.DIRECTORY_SEPARATOR.$sFileName));
				try {
					$oParser->parse()->__toString();
				} catch(Exception $e) {
					$this->fail($e);
				}
			}
			closedir($rHandle);
		}
	}
	
	/**
	* @depends testCssFiles
	*/
	function testColorParsing() {
		$oDoc = $this->parsedStructureForFile('colortest');
		foreach($oDoc->getAllRuleSets() as $oRuleSet) {
			if(!$oRuleSet instanceof CSSDeclarationBlock) {
				continue;
			}
			$sSelector = $oRuleSet->getSelectors();
			$sSelector = $sSelector[0]->getSelector();
			if($sSelector == '#mine') {
				$aColorRule = $oRuleSet->getRules('color');
				$aValues = $aColorRule['color']->getValues();
				$this->assertSame('red', $aValues[0][0]);
				$aColorRule = $oRuleSet->getRules('background-');
				$aValues = $aColorRule['background-color']->getValues();
				$this->assertEquals(array('r' => new CSSSize(35.0), 'g' => new CSSSize(35.0), 'b' => new CSSSize(35.0)), $aValues[0][0]->getColor());
				$aColorRule = $oRuleSet->getRules('border-color');
				$aValues = $aColorRule['border-color']->getValues();
				$this->assertEquals(array('r' => new CSSSize(10.0), 'g' => new CSSSize(100.0), 'b' => new CSSSize(230.0), 'a' => new CSSSize(0.3)), $aValues[0][0]->getColor());
				$aColorRule = $oRuleSet->getRules('outline-color');
				$aValues = $aColorRule['outline-color']->getValues();
				$this->assertEquals(array('r' => new CSSSize(34.0), 'g' => new CSSSize(34.0), 'b' => new CSSSize(34.0)), $aValues[0][0]->getColor());
			}
		}
		foreach($oDoc->getAllValues('background-') as $oColor) {
			if($oColor->getColorDescription() === 'hsl') {
				$this->assertEquals(array('h' => new CSSSize(220.0), 's' => new CSSSize(10.0), 'l' => new CSSSize(220.0)), $oColor->getColor());
			}
		}
		foreach($oDoc->getAllValues('color') as $sColor) {
			$this->assertSame('red', $sColor);
		}
	}
	
	function testUnicodeParsing() {
		$oDoc = $this->parsedStructureForFile('unicode');
		foreach($oDoc->getAllDeclarationBlocks() as $oRuleSet) {
			$sSelector = $oRuleSet->getSelectors();
			$sSelector = $sSelector[0]->getSelector();
			if(substr($sSelector, 0, strlen('.test-')) !== '.test-') {
				continue;
			}
			$aContentRules = $oRuleSet->getRules('content');
			$aContents = $aContentRules['content']->getValues();
			$sCssString = $aContents[0][0]->__toString();
			if($sSelector == '.test-1') {
				$this->assertSame('" "', $sCssString);
			}
			if($sSelector == '.test-2') {
				$this->assertSame('"é"', $sCssString);
			}
			if($sSelector == '.test-3') {
				$this->assertSame('" "', $sCssString);
			}
			if($sSelector == '.test-4') {
				$this->assertSame('"𝄞"', $sCssString);
			}
			if($sSelector == '.test-5') {
				$this->assertSame('"水"', $sCssString);
			}
			if($sSelector == '.test-6') {
				$this->assertSame('"¥"', $sCssString);
			}
			if($sSelector == '.test-7') {
				$this->assertSame('"\A"', $sCssString);
			}
			if($sSelector == '.test-8') {
				$this->assertSame('"\"\""', $sCssString);
			}
			if($sSelector == '.test-9') {
				$this->assertSame('"\"\\\'"', $sCssString);
			}
			if($sSelector == '.test-10') {
				$this->assertSame('"\\\'\\\\"', $sCssString);
			}
			if($sSelector == '.test-11') {
				$this->assertSame('"test"', $sCssString);
			}
		}
	}

	function testSpecificity() {
		$oDoc = $this->parsedStructureForFile('specificity');
		$oDeclarationBlock = $oDoc->getAllDeclarationBlocks();
		$oDeclarationBlock = $oDeclarationBlock[0];
		$aSelectors = $oDeclarationBlock->getSelectors();
		foreach($aSelectors as $oSelector) {
			switch($oSelector->getSelector()) {
				case "#test .help":
					$this->assertSame(110, $oSelector->getSpecificity());
				break;
				case "#file":
					$this->assertSame(100, $oSelector->getSpecificity());
				break;
				case ".help:hover":
					$this->assertSame(20, $oSelector->getSpecificity());
				break;
				case "ol li::before":
					$this->assertSame(3, $oSelector->getSpecificity());
				break;
				case "li.green":
					$this->assertSame(11, $oSelector->getSpecificity());
				break;
				default:
					$this->fail("specificity: untested selector ".$oSelector->getSelector());
			}
		}
		$this->assertEquals(array(new CSSSelector('#test .help', true)), $oDoc->getSelectorsBySpecificity('> 100'));
	}

	function testManipulation() {
		$oDoc = $this->parsedStructureForFile('atrules');
		$this->assertSame('@charset "utf-8";@font-face {font-family: "CrassRoots";src: url("../media/cr.ttf");}html, body {font-size: 1.6em;}', $oDoc->__toString());
		foreach($oDoc->getAllDeclarationBlocks() as $oBlock) {
			foreach($oBlock->getSelectors() as $oSelector) {
				//Loop over all selector parts (the comma-separated strings in a selector) and prepend the id
				$oSelector->setSelector('#my_id '.$oSelector->getSelector());
			}
		}
		$this->assertSame('@charset "utf-8";@font-face {font-family: "CrassRoots";src: url("../media/cr.ttf");}#my_id html, #my_id body {font-size: 1.6em;}', $oDoc->__toString());

		$oDoc = $this->parsedStructureForFile('values');
		$this->assertSame('#header {margin: 10px 2em 1cm 2%;font-family: Verdana, Helvetica, "Gill Sans", sans-serif;font-size: 10px;color: red !important;}body {color: green;font: 75% "Lucida Grande", "Trebuchet MS", Verdana, sans-serif;}', $oDoc->__toString());
		foreach($oDoc->getAllRuleSets() as $oRuleSet) {
			$oRuleSet->removeRule('font-');
		}
		$this->assertSame('#header {margin: 10px 2em 1cm 2%;color: red !important;}body {color: green;}', $oDoc->__toString());
	}

	function testSlashedValues() {
		$oDoc = $this->parsedStructureForFile('slashed');
		$this->assertSame('.test {font: 12px/1.5;border-radius: 5px 10px 5px 10px/10px 5px 10px 5px;}', $oDoc->__toString());
	}
	
	function parsedStructureForFile($sFileName) {
		$sFile = dirname(__FILE__).DIRECTORY_SEPARATOR.'files'.DIRECTORY_SEPARATOR."$sFileName.css";
		$oParser = new CSSParser(file_get_contents($sFile));
		return $oParser->parse();
	}
}
