name: 'Require Tests'

on:
  pull_request_target:
    types: [opened]

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: infection/tests-checker-action@v1.0.2
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            comment: Could you please add tests to make sure this change works as expected?
            fileExtensions: '.php'
            testDir: 'tests'
            testPattern: '*Test.php'
