name: 'Require Tests on Code Change'

on:
  pull_request_target:
    types: [opened]

jobs:
  check:
    name: 'Require Tests on Code Change'

    runs-on: ubuntu-22.04

    steps:
        - name: "Execute tests-checker-action"
          uses: infection/tests-checker-action@v1.0.2
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            comment: Could you please add tests to make sure this change works as expected?
            fileExtensions: '.php'
            testDir: 'tests'
            testPattern: '*Test.php'
